---
functional:
  - Пользователи должны иметь возможность создавать и присоединяться к играм, где они могут соревноваться друг с другом в решении задач.
  - Игроки должны видеть код друг друга в реальном времени
  - Реализовать систему рейтингов, где пользователи могут видеть свои достижения и сравнивать их с другими игроками.
  - Возможность игры с ботом, который будет предоставлять пользователю возможность тренироваться.
  - Возможность приглашения друга для игры по ссылке.
  - Пользователи должны иметь доступ к разнообразным задачам для решения, с возможностью фильтрации по сложности.
  - Реализовать чат для общения между игроками во время игры.
  - Предоставление пользователям статистики по их играм, включая время решения задач и количество ошибок.
non-functional:
  - Интерфейс должен быть интуитивно понятным и удобным для пользователей разного уровня подготовки.
  - Время загрузки страниц не должно превышать 2 секунд при нормальном интернет-соединении.
  - Все данные пользователей должны быть защищены с использованием современных методов шифрования.
  - Сайт должен корректно отображаться и функционировать на мобильных устройствах.
  - Сайт должен быть протестирован на последних версиях популярных браузеров (Chrome, Firefox, Safari, Edge).
  - Система должна быть способна обрабатывать минимум 1000 одновременных пользователей без значительных задержек.
implicit:
  - Необходимо обеспечить возможность для пользователей вносить предложения и идеи по улучшению проекта.
  - Реализовать механизм сбора обратной связи от пользователей для постоянного улучшения функционала.
